Repository macbre/phantomas, pull requests merged in 2020-10, with the labels that each got.

#784 Add support for viewport option
  extensions/viewport/viewport.js
  test/integration-spec.yaml
  test/webroot/viewport.html
Labels: Chrome-headless, enhancement

#786 Tests: use the latest macbre/nginx-brotli - 1.19.3
  test/integration-spec.yaml
  test/nginx-docker-compose.yaml
Labels: internals

#787 Adjustments to lazyloadable images
  lib/browser.js
  modules/lazyLoadableImages/scope.js
  test/integration-spec.yaml
  test/webroot/lazy-loadable-images.html
  test/webroot/static/150x100.jpg
  test/webroot/static/75x120.jpg
  test/webroot/static/75x50.jpg
Labels: bug

#793 core/scope.js: log window URL and whether it is an iframe
  core/scope.js
Labels: internals

#803 Update CI build names
  .github/workflows/dockerimage.yml
  .github/workflows/linter.yml
  .github/workflows/tests.yml
Labels: internals

#808 Makes tests crash on unhandled rejections instead of silently ignoring them
  .prettierignore
  Dockerfile
  lib/browser.js
  test/integration-spec.yaml
  test/integration-test-extra.js
  test/integration-test.js
  test/module-test.js
  test/modules/cacheHits-test.js
  test/modules/caching-test.js
  test/modules/domains-test.js
  test/modules/keepAlive-test.js
  test/modules/mainRequest-test.js
  test/modules/mock.js
  test/modules/redirects-test.js
  test/modules/requestsMonitor-test.js
  test/modules/requestsStats-test.js
  test/modules/staticAssets-test.js
  test/nginx-docker-compose.yaml
  test/results-test.js
Labels: internals

#814 CI: cache npm dependencies
  .github/workflows/linter.yml
  .github/workflows/tests.yml
Labels: internals

#815 Docker | build using Node.js 15.x and Chromium 86
  .github/workflows/tests.yml
  Dockerfile
Labels: docker
