Repository macbre/phantomas, pull requests merged in 2020-12, with the labels that each got.

#836 Fix pragma: no-cache automatically added to all requests
  core/modules/requestsMonitor/requestsMonitor.js
  modules/blockDomains/blockDomains.js
  test/integration-spec.yaml
  test/webroot/browser-caching.html
Labels: bug

#841 Expose CPU related metrics from page.metrics() as phantomas metrics
  docs/metrics.md
  lib/metadata/metadata.json
  modules/cpuTasks/cpuTasks.js
Labels: new metric

#840 Fix error with blob urls
  core/modules/requestsMonitor/requestsMonitor.js
Labels: bug

#842 Use Docker layers cache to speed up CI builds
  .github/workflows/dockerimage.yml
Labels: internals
