Repository macbre/phantomas, pull requests merged in 2021-01, with the labels that each got.

#843 Fix object errors
  lib/index.js
  test/integration-spec.yaml
  test/webroot/svg-as-object.html
Labels: bug

#847 Fix for neverending runs
  extensions/screenshot/screenshot.js
  lib/browser.js
  modules/analyzeCss/analyzeCss.js
  test/integration-spec.yaml
  test/webroot/js-redirect.html
Labels: bug

#848 Use BuildKit
  .github/workflows/dockerimage.yml
Labels: docker, internals

#849 Use BUILDKIT_INLINE_CACHE
  .github/workflows/dockerimage.yml
Labels: docker, internals

#855 Detect MP4 videos
  core/modules/requestsMonitor/requestsMonitor.js
  test/integration-spec.yaml
  test/webroot/static/stickman.mp4
  test/webroot/static/stickman.webm
  test/webroot/videos.html
Labels: enhancement
