Repository macbre/phantomas, pull requests merged in 2021-03, with the labels that each got.

#876 Label the image with git URL and commit hash
  .github/workflows/dockerimage.yml
  Dockerfile
  hooks/build
Labels: docker

#903 Use macbre/nginx-brotli:1.19.8
  test/nginx-docker-compose.yaml
Labels: internals

#904 CLI - make sure options are not "camelCased" but "have-dashes" instead
  bin/phantomas.js
  bin/utils.js
  package-lock.json
  package.json
  test/bin-utils-test.js
Labels: bug

#910 Accept absolute paths for screenshots
  extensions/screenshot/screenshot.js
  test/integration-spec.yaml
  test/integration-test-extra.js
Labels: enhancement

#906 Refactor bin/program.js script
  bin/phantomas.js
  bin/program.js
  lib/browser.js
  test/bin-program-test.js
  test/integration-spec.yaml
Labels: internals

#912 Removed dead link from readme
  README.md
Labels: docs

#913 Handle some unhandled exceptions
  lib/browser.js
Labels: aws-lambda, bug

#917 Detect if ran from an AWS Lambda and set additional Chrome flags
  lib/browser.js
Labels: aws-lambda
