Repository macbre/phantomas, pull requests merged in 2021-02, with the labels that each got.

#854 Add a full page screenshot option and make it false by default
  bin/phantomas.js
  extensions/screenshot/screenshot.js
Labels: enhancement

#871 CI - use macbre/nginx-brotli:1.19.7
  test/nginx-docker-compose.yaml
Labels: internals

#872 Dockerfile - use node:lts-alpine3.13 and Chromium 88
  Dockerfile
Labels: docker
