Repository macbre/phantomas, pull requests merged in 2023-07, with the labels that each got.

#1292 bump puppeteer to v20.8.0
  package-lock.json
  package.json
Labels: external dependency

#1291 (fix) Browser not properly closing
  lib/browser.js
Labels: bug

#1293 bump puppeteer to v20.8.1
  package-lock.json
  package.json
Labels: external dependency

#1297 bump puppeteer to v20.8.3
  package-lock.json
  package.json
Labels: external dependency

#1298 bump puppeteer to v20.9.0
  package-lock.json
  package.json
Labels: external dependency

#1299 Add AVIF as an image type
  core/modules/requestsMonitor/requestsMonitor.js
  test/modules/requestsMonitor.test.js
Labels: enhancement

#1296 Fix a false JSError reported by Phantomas
  modules/domQueries/scope.js
  test/webroot/js-errors.html
Labels: bug
