Repository macbre/phantomas, pull requests merged in 2023-09, with the labels that each got.

#1311 bump puppeteer to v21.1.1
  package-lock.json
  package.json
Labels: external dependency

#1318 CI - test using the LTS and the latest version of Node.js
  .github/workflows/linter.yml
  .github/workflows/npmpublish.yml
  .github/workflows/tests.yml
Labels: internals

#1319 integration-spec.yaml: mark "httpbin's /basic-auth" as flaky
  test/integration-spec.yaml
Labels: Tests

#1316 Fix issue with native lazyloading not recognized
  modules/lazyLoadableImages/scope.js
  test/webroot/lazy-loadable-images.html
Labels: bug

#1320 bump puppeteer to v21.2.1
  package-lock.json
Labels: external dependency

#1321 bump puppeteer to v21.3.1
  package-lock.json
  package.json
Labels: external dependency

#1322 bump puppeteer to v21.3.4
  package-lock.json
  package.json
Labels: external dependency

#1323 bump puppeteer to v21.3.5
  package-lock.json
  package.json
Labels: external dependency

#1324 bump puppeteer to v21.3.6
  package-lock.json
  package.json
Labels: external dependency
